### ISSUE TITLE
[TPB_helper] Sort order is messed up when search results are sorted by "date uploaded"

### ISSUE THREAD

**Issue by NitroV** [darkred/Userscripts#18]
**Describe the bug**

The sort order is all over the place once search results are sorted by the date uploaded.

**To Reproduce**

1. Search for anything
2. Click on "Uploaded" column

**Expected behavior**

Should be in proper ascending or descending order 

**Screenshots**

![image](https://user-images.githubusercontent.com/73184871/105818720-41209e80-5fdd-11eb-8e02-e7d24187b851.png)

**Desktop (please complete the following information):**

 - OS: Win7ProX64SP1
 - Browser Chromium 88.0.4324.104
 - Version Script-2020.7.30/Violentmonkey-2.12.9

**Additional context**

The above screenshot shows when results are sorted in ascending order, it simply inverts when clicked again. Still incorrect.

Unrelated to the issue/Enhancement:

Please consider including dark theme for tpb as a part of helper extension. Themes can be found [here](https://userstyles.org/styles/browse/thepiratebay), [here](https://github.com/Carlgo11/thepiratebay-clean) or [here](https://greasyfork.org/en/scripts/415797-piratebay-darkmode).

**Comment by darkred** [comment]
This is rather complicated:

- Regarding the generated `Ratio` column:
  - initially the search results tables were not sortable at all. 
  - I was using the tablesorter jquery plugin just to make the generated `Ratio` column sortable alone.
  - Recently (June 2020) the pages (all columns) are now sortable built-in, that's why I removed that functionality, as it was only meant for the Ratio column.
- Regarding the `Uploaded` column:
  - The script converts the `Uploaded` column to relative format.
The built-in sorting functionality takes these values as plain text, not taking account the actual durations, 
and sorts them alphabetically - in your screenshot, in reverse it would be:
    ```
    6 months ago
    6 years ago
    7 months ago 
    8 years ago 
    Today 
    ```

<br/>

There's nothing I can do to fix this:
> tablesorter works on standard HTML tables (with THEAD and TBODY tags)

but the tpb search result tables are not standard.

I can't make tablesorter work only on a single column,
nor disable the built-in sorting, then convert the whole table to standard 
(it would break the tables styling/layout, among other things).

<br/>

I can only suggest to either avoid clicking to sort by the `Uploaded` header,
or comment out line 383 of the script (`convertDates();`) to disable getting relative dates in search results.
(*the `Display torrent timestamps in relative format:` setting affects timestamps in torrent pages, not search results*)



---

Regarding your suggestion, I use this userstyle https://userstyles.org/styles/150101/simple-dark-tpb
and it's working fine, it applies even to TPB Helper settings, no need to add a theme to the script.
