### ISSUE TITLE
[Suggestion] [Rarbg Various tweaks] Add a way to show thumbnails & previews let the user control the size of it! 

### ISSUE THREAD

**Issue by Droyk** [darkred/Userscripts#26]
Hey, I've been using your script a lot lately and find it really convenient. if possible can you add a way to show thumbnails or bigger previews instead of icons for e.g 
![rarbgunblocked org_torrents php_category=movies (1)](https://user-images.githubusercontent.com/15848350/115980406-1fb65b00-a5aa-11eb-83ff-2b3466b6b710.png)

in the above image you can see instead of icons there is a thumbnail and when the user mouse hovers over the title or the thumbnail the complete image in max resolution shows up. 
I want you to add this feature in a way so the user can control the size of both the mouse hover and the thumbnail.

additionally, instead of showing max resolution on mouse hover over the title, you can add an option to show the image preview that is submitted in the description box. 
![image](https://user-images.githubusercontent.com/15848350/115980532-14176400-a5ab-11eb-9a6b-af813b4c4b95.png)
this will save a lot of users time, especially mine. coz I browse on xxx category a lot. and I want to see the image previews and to see them I have to open them in the background tab which consumes time, memory, & cpu power especially when you're working with many tabs! 

also, I have been using [infy scroll](https://chrome.google.com/webstore/detail/infy-scroll/gdnpnkfophbmbpcjdlbiajpkgdndlino) it's a chrome extension that lets the user to infinite scroll the website instead of going through page by page. it works fabulously on Rarbg. I want you to make this feature compatible with the extension.

**Comment by darkred** [comment]
> I want you to ___

First of all, that is *not* a nice way to word a feature request... It sounds more like a boss giving an order to the employee.

Please keep in mind that the code in this repo is free, open-source, and you are asking its author to spend his *spare* time for you. 
You can always fork it and modify it as you wish on your own.

---

Secondly, in the Screenshot there's a `Poster` column that's not by the site.
You're using some userscript/extension that you didn't mention.

---

In any case, regarding your suggestions I can only suggest the following:

> show thumbnails or bigger previews instead of icons

> so the user can control the size of ~both the mouse hover and~ the thumbnail.

Use this fine script [RARBG Advanced Filters](https://greasyfork.org/en/scripts/29661-rarbg-advanced-filters)


&nbsp;

> additionally, instead of showing max resolution on mouse hover over the title, you can add an option to show the image preview that is submitted in the description box.

The image previews inside each page are not hosted in rarbg, they are in various image hosting sites.
So, there's no one solution fits all.

What I suggest is this great script [Mouseover Popup Image Viewer](https://greasyfork.org/en/scripts/394820-mouseover-popup-image-viewer) with this custom rule:

```json
{"d": "rarbg",
 "r": "torrent/[\\w]+",
 "q": "#description img"
}

```

and may try this too: [RARBG Helper](https://greasyfork.org/en/scripts/396019-rarbg-helper)



&nbsp;

> also, I have been using infy scroll it's a chrome extension that lets the user to infinite scroll the website instead of going through page by page. it works fabulously on Rarbg. I want you to make this feature compatible with the extension.

I'm not interested in infinite scrolling,
because none of my rarbg scripts would be applied in the paginated content.

**Comment by Droyk** [comment]
>First of all, that is not a nice way to word a feature request... It sounds more like a boss giving orders to the employee.

>Please keep in mind that the code in this repo is free, open-source, and you are asking its author to spend his spare time for you.
You can always fork it and modify it as you wish on your own.

Forgive me that not what I meant! I'm not good English speaker. it's my third language. I'm not good at writing it. 
I can understand pretty well though so I really apologize if that how it sounds. & I'm not a developer. I am an average person who just likes to be computer savvy that's all

>Secondly, in the Screenshot there's a Poster column that's not by the site.
You're using some userscript/extension that you didn't mention.

Yes I am and this is the one https://openuserjs.org/meta/Somchai/Show_Poster_Rarbg.meta.js
>Use this fine script RARBG Advanced Filters
I have used it before. it's not what I want.

>What I suggest is this great script Mouseover Popup Image Viewer with this custom rule:

{"d": "rarbg",
 "r": "torrent/[\\w]+",
 "q": "#description img"
}
Thank you for this. 

> none of my rarbg scripts would be applied in the paginated content.

Hmm, why not?  is there is a limitation of some kind that doesn't let you apply your scripts in the paginated content?

**Comment by darkred** [comment]
> Forgive me that not what I meant! I'm not good English speaker. it's my third language. I'm not good at writing it.
> I can understand pretty well though so I really apologize if that how it sounds. & I'm not a developer. I am an average person who just likes to be computer savvy that's all

Ok, no problem, everything's cool then, thank you 👍 

---

> Hmm, why not? is there is a limitation of some kind that doesn't let you apply your scripts in the paginated content?

The scripts in their current state, only apply to the initial content, i.e. the 1st page content.

If there was infinite scrolling,
the paginated content (the HTML code of each next page) would be appended to the initial content, below the first page.
But, since's never any change in the address bar as you scroll, the scripts wouldn't apply to the paginated content.

*If* I wanted to have infinite scrolling with my rarbg scripts, I would: 
- use the [jScroll](https://greasyfork.org/en/scripts/11636-jscroll) js library in my 'Various Tweaks' script [I wouldn't not rely on/support any extension], 
- have to modify all my 3 rarbg scripts (or, combine them into one) to also watch for paginated/appended content (making sure that they are only applied once per paginated page).

All this is not worth the trouble for me, because I rarely if ever get past the 1nd page of any rarbg list. Sorry.

**Comment by Droyk** [comment]
>All this is not worth the trouble for me, because I rarely if ever get past the 1nd page of any rarbg list. Sorry.

sad.
if possible can I make this script https://openuserjs.org/meta/Somchai/Show_Poster_Rarbg.meta.js work with the extension? can you guide me in the right direction? please tell me what do I need to learn first to make this possible by myself?
I always wanted to be a developer seems like it's a great time to start learning it! 
it will take months but I want to see if I'm cut for it or not!

if it helps 
> this extension is compatible with the AutoPagerize Database, which means it supports thousands of websites automatically. Infy supports 4 different actions and 4 different append modes so you can customize each site's infinite scrolling to how you want it to be. Infy understands both CSS Selector and XPath rules for finding next links. It can also increment URLs and perform special actions, like clicking "Load More" buttons. You can save your settings for each URL and Infy will auto-activate the next time you visit them.

Source: https://github.com/roysix/infy-scroll

**Comment by darkred** [comment]
You have to be familiar with CSS (and XPath) and some basic JavaScript to do this.

---

From the rarbg rule in the [AutoPagerize Database](http://wedata.net/databases/AutoPagerize/items_all.json):
keep the `pageElement` and `nextLink` XPath selectors in mind.
```json
    "pageElement": "//table[@class='lista2t']/tbody/tr[td/@class='lista']",
    "nextLink": "//a[@title='next page']",
```


Then for every table row that the script applies to, do something like:

`modifiedElement.classList.add('done');`

then find a way (probably jQuery) to select all the paginated content,
e.g. 
for page 2: the `#infy-scroll-divider-2` seperator element + all following `pageelement` table rows
for page 3: the `#infy-scroll-divider-3` seperator element + all following `pageelement` table rows
and so on

and call the script again on each page content, and do something like this:

```js
if (!someSelector.contains("done"){
   // do the work
}
```

That's all I can offer.

If everything fails, maybe making a request in https://greasyfork.org/en/discussions/requests

**Comment by Droyk** [comment]
Thank you!
