### ISSUE TITLE
[ProtonMail - remove forced signature] The script no longer works

### ISSUE THREAD

**Issue by wuniversales** [darkred/Userscripts#43]
### Please ensure:

- [X] I included in the issue title the script name I'm referring to.
- [X] I performed a search of the [issue tracker](https://github.com/darkred/Userscripts/issues) and in the relevant Greasyfork [feedback page](https://greasyfork.org/en/users/2160-darkred?sort=updated) to avoid opening a duplicate issue.
- [X] The bug is caused by the script itself. It doesn't happen if I disable the script, or in a fresh browser profile.

### Describe the problem and how to replicate it

Hi, the script again doesn't work, I guess it's due to the new protonmail update.
Greetings

### Example URL

https://mail.protonmail.com

### Script Manager

Tampermonkey

### Browser(s) used

Firefox latest version

**Comment by darkred** [comment]
Hi.

Unfortunately the script doesn't work with Firefox. *I describe all my efforts about this [here](https://github.com/darkred/Userscripts/issues/13#issuecomment-739492052)*. It works only with Chrome (TM/VM).

You haven't given any feedback in [your last issue](https://github.com/darkred/Userscripts/issues/27#issuecomment-857140170). 
And, you hadn't clarified there that you use Firefox, otherwise I'd reply in there.

I just added in script description that the script only works in Chrome (TM/VM).
