### ISSUE TITLE
[1337x_-_torrent_and_magnet_links] Would it be possible to make the torrent files/links available without clicking on them first?

### ISSUE THREAD

**Issue by mjrawesome** [darkred/Userscripts#51]
### Please ensure:

- [X] I included in the issue title the script name I'm referring to.
- [X] Before you request from me to write a new script for you, check in https://greasyfork.org/en/scripts and https://openuserjs.org/ : what you ask might be there already.

### Description

Thanks for developing this script. It's very useful.

I have the following problem, though. I want to download all torrents from a 1337x page using an extension like DownloadThemAll or uSelect iDownload and your/NotNeo script. However, without clicking on the torrent icon (generated by your script) first, the actual links to torrent files aren't picked up by the extensions at all. After clicking on the torrent icon once for a particular torrent, the correct link for that torrent is available and visible instead of `javascript:void(0)`.

Would it be possible to make the torrent files/links available without clicking on them first?

### Example URL

https://1337x.to/sort-search/Power+BI/time/desc/1/

**Comment by darkred** [comment]
You are welcome!

My answer is the basically the same as https://greasyfork.org/en/scripts/23493-rarbg-torrent-and-magnet-links/discussions/130604

You could try the following in Console:

```js
var interval = 1;
document.querySelectorAll('.list-button-magnet').forEach((el) => { 
    setTimeout(function(){
    el.click() 
    }, interval += 1000);
    // console.log(interval)
})
```

This would click all ML links sequentially with 1 sec delay, but it will result in clicking *most* of the ML links, but inevitably some links with show `Not allowed to launch 'magnet::' because a user gesture is required`, something which is an anti-flooding feature in Chromium and can't be avoided.

You can't click all DL links sequentially because they redirect the page to itorrents.org.
